{% set version = "0.8.2" %}

package:
  name: theano
  version: {{ version }}

source:
  git_url: https://github.com/Theano/Theano.git
  git_tag: rel-{{ version }}
  patches:
    - 0001-Conda-Fix-and-unify-conda-mkl-detection-and-instruct.patch
    - 0002-Conda-Search-in-sys.prefix-Library-bin-not-sys.prefi.patch
    - 0003-Conda-Enable-use-of-mingw-w64-g-and-mkl-when-not-on-.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - m2-filesystem      # [win]
    - m2-git             # [win]
    - git                # [not win]
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.3.0
    - scipy >=0.7.0

  run:
    - python
    - m2w64-toolchain    # [win]
    - mkl-service        # [win or linux]
    - libpython >=2.0    # [win]
    - six >=1.9.0
    - numpy >=1.3.0
    - scipy >=0.7.0

test:
  requires:
    - nose >=1.3.0
    - nose-parameterized >=0.5.0

  imports:
    - theano
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.gof
    - theano.gof.tests
    - theano.misc
    - theano.sandbox
    - theano.sandbox.cuda
    - theano.sandbox.cuda.tests
    - theano.scalar
    - theano.scalar.tests
    - theano.sparse
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests

about:
  home: http://deeplearning.net/software/theano/
  license: BSD 3-Clause
  summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.

extra:
  recipe-maintainers:
    - jakirkham
